spring:
  application:
    name: object
  threads:
    virtual:
      enabled: true

  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/cinema
    username: test
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver